### ISSUE TITLE
Improve output when specified parameter is not found

### ISSUE THREAD

**Issue by tasleson** [stratis-storage/stratis-cli#167]
When you specify an argument which doesn't exist the output could clearer, some examples:

```
# bin/stratis blockdev list no_such_pool
Execution failure caused by:
No unique item found among returned matches: ()
```
```
# bin/stratis pool destroy no_such_pool
Execution failure caused by:
No unique item found among returned matches: ()
```

```
# bin/stratis filesystem create no_such_pool some_fs
Execution failure caused by:
No unique item found among returned matches: ()
```

```
# bin/stratis filesystem destroy no_such_pool some_fs
Execution failure caused by:
No unique item found among returned matches: ()
```

**Comment by mulkieran** [comment]
Please run with ```--propagate``` flag as well.

**Comment by tasleson** [comment]
```
# bin/stratis --propagate pool destroy no_such_pool
Traceback (most recent call last):
  File "/home/tasleson/projects/stratis/stratis-cli/src/stratis_cli/_main.py", line 42, in the_func
    result.func(result)
  File "/home/tasleson/projects/stratis/stratis-cli/src/stratis_cli/_actions/_top.py", line 97, in destroy_pool
    }).search(managed_objects))
  File "/home/tasleson/projects/stratis/stratis-cli/src/stratis_cli/_actions/_data.py", line 237, in unique
    raise StratisCliUniqueLookupError(result)
stratis_cli._errors.StratisCliUniqueLookupError: No unique item found among returned matches: ()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/stratis", line 33, in <module>
    main()
  File "bin/stratis", line 29, in main
    return run()(sys.argv[1:])
  File "/home/tasleson/projects/stratis/stratis-cli/src/stratis_cli/_main.py", line 46, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['--propagate', 'pool', 'destroy', 'no_such_pool'] which were parsed to Namespace(func=<function TopActions.destroy_pool at 0x7f1ec90179d8>, pool_name='no_such_pool', propagate=True) failed
```

**Comment by mulkieran** [comment]
What should the user see instead?

**Comment by tasleson** [comment]
Something like:

`"Pool: no_such_pool not found"`

**Comment by mulkieran** [comment]
We probably want to decorate the synthesized methods, i.e., pools, filesystems, etc., so that they call unique internally. This is probably doable.

**Comment by mulkieran** [comment]
```
def pools(props=None, unique=false):
    stuff = old_pools(props)
    if unique:
       try:
           unique(stuff)
       except Unique... as err:
            #raise newly created exception that says
                 "Unable to find the pool matching specification <props>" 
    else:
       return stuff
```

Then calling code would look like:

```
(pool_object_path, _) =
  pools(props={'Name' : namespace.pool_name}, unique=True}).search(managed_objects)
```

Name of error is ```StratisCliLookupError```, and fields are the properties used to lookup and whether or not uniqueness was requested and the D-Bus interface being matched on.

**Comment by mulkieran** [comment]
Ok. What we want to do is modify the search method of the GMOQuery object that we generated by, e.g., invoking pools().

**Comment by tomuxi** [comment]
Similar problem with fs destroy when referring to an existing pool but missing filesystem: no error output at all. For example: stratis fs destroy existing-pool non-existing-fs .

**Comment by mulkieran** [comment]
> Similar problem with fs destroy when referring to an existing pool but missing filesystem: no error output at all. For example: stratis fs destroy existing-pool non-existing-fs .

Hi thanks. This is not the same issue, but is due to the fact that we assumed that idempotent behavior would be preferable in these situations. But we found at that most people don't believe that, and so we have an outstanding bz for the problem which we plan to address in the near future:
https://bugzilla.redhat.com/show_bug.cgi?id=1687869.
