### ISSUE TITLE
pool list displays - "Execution failed:"

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratis-cli#191]
This can be reproduced on : dell-r730-011.dsal.lab.eng.rdu2.redhat.com

Create 10 filesystems and 10 snapshots.  Start fio on the filesystems to write 2 gig each.

Without the --propagate flag:
```
# stratis pool list
Execution failed: 
#
```

With the --propagate flag:

```
# stratis --propagate pool list
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dbus_python_client_gen-0.6-py3.6.egg/dbus_python_client_gen/_invokers.py", line 304, in dbus_func
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/stratis", line 4, in <module>
    __import__('pkg_resources').run_script('stratis-cli==0.5.0', 'stratis')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1531, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-0.5.0-py3.6.egg/EGG-INFO/scripts/stratis", line 33, in <module>
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-0.5.0-py3.6.egg/EGG-INFO/scripts/stratis", line 29, in main
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-0.5.0-py3.6.egg/stratis_cli/_main.py", line 39, in the_func
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-0.5.0-py3.6.egg/stratis_cli/_actions/_top.py", line 73, in list_pools
  File "/usr/local/lib/python3.6/site-packages/dbus_python_client_gen-0.6-py3.6.egg/dbus_python_client_gen/_invokers.py", line 306, in dbus_func
dbus_python_client_gen._errors.DPClientInvocationError
```

**Comment by mulkieran** [comment]
Thanks for putting up this report. I think it's just a question of versions. If you are able to update to more recent version of stratis-cli and dbus-python-client-gen you should see more friendly behavior both w/ and w/out the propagate flag set.

**Comment by trgill** [comment]
updated to the latest CLI and it doesn't happen.  sorry for the noise.
