### ISSUE TITLE
Consider changing output on error

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#268]
The suggestion is that, if an explanation exists, that only the explanation be printed, and otherwise the stacktrace be allowed to propagate. See #168 for prior discussion.

**Comment by mulkieran** [comment]
We can even first print an explanation that the error is unexpected, and then allow the stack trace to appear.

**Comment by mulkieran** [comment]
New view if explanation is available:

```
[mulhern@localhost ~/stratis2/stratis-cli (master)]$ PYTHONPATH=./src ./bin/stratis pool create n /d
Execution failed:
Most likely stratis is unable to connect to the stratisd D-Bus service.
[mulhern@localhost ~/stratis2/stratis-cli (master)]$ echo $?
1
```

**Comment by mulkieran** [comment]
New view if explanation is available:

```
$ PYTHONPATH=./src ./bin/stratis pool create n /d
Execution failed:
Most likely stratis is unable to connect to the stratisd D-Bus service.
$ echo $?
1
```

**Comment by mulkieran** [comment]
New view if explanation is not available (I had to engineer the error, because things are pretty well covered in the CLI):

```
$ PYTHONPATH=./src ./bin/stratis pool create n /d
stratis encountered an unexpected error during execution. Please report the error at https://github.com/stratis-storage/stratis-cli, and include the stack trace below.

Traceback (most recent call last):
  File "/home/mulhern/stratis2/stratis-cli/src/stratis_cli/_main.py", line 48, in the_func
    result.func(result)
  File "/home/mulhern/stratis2/stratis-cli/src/stratis_cli/_actions/_top.py", line 50, in create_pool
    raise DPClientInvocationError("some message", "pool", "j")
dbus_python_client_gen._errors.DPClientInvocationError: some message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./bin/stratis", line 35, in <module>
    main()
  File "./bin/stratis", line 31, in main
    return run()(sys.argv[1:])
  File "/home/mulhern/stratis2/stratis-cli/src/stratis_cli/_main.py", line 57, in the_func
    handle_error(err)
  File "/home/mulhern/stratis2/stratis-cli/src/stratis_cli/_error_reporting.py", line 151, in handle_error
    raise err
  File "/home/mulhern/stratis2/stratis-cli/src/stratis_cli/_main.py", line 52, in the_func
    raise StratisCliActionError(command_line_args, result) from err
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['pool', 'create', 'n', '/d'] which were parsed to Namespace(blockdevs=['/d'], func=<function TopActions.create_pool at 0x7fdcdda89c80>, pool_name='n', propagate=False, redundancy='none') failed
$ echo $?
1
```
