### ISSUE TITLE
Make stratisd_cert.py tests more expressive on failure

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/stratis-cli#516]
We can do this by using the ```msg``` argument to ```unittest.assertEqual```.

Wherever there is a failure in an explicit call on the D-Bus to a stratisd D-Bus method we should actually display the error message whatever it is.

So, here is an example:

```
    def test_pool_destroy(self):
        """
        Test destroying a pool.
        """
        pool_name = p_n()
        make_test_pool(pool_name, StratisCertify.DISKS[0:1])

        (_, return_code, _) = StratisDbus.pool_destroy(pool_name)
        self.assertEqual(return_code, dbus.UInt16(0))

        self.assertEqual(StratisDbus.fs_list(), {})
```

We would want to change the pair of lines where ```pool_destroy``` is invoked to these:

```
(_, return_code, msg) = StratisDbus.pool_destroy(pool_name)
self.assertEqual(return_code, dbus.UInt16(0), msg=msg)
```

and so forth in other places as appropriate.

We might as well generalize this to a method as in stratis_cli_cert.py.
So, make a method more or less like the one below, and then use as appropriate.

```
def unittest_command(self, result, expected_return_code):
    """
    :param result: a tuple of the (optional) return value, the return code, and the return message from a D-Bus call
    :type result: tuple of object * dbus.UInt16 * str OR tuple of dbus.UInt16 * str if there is no return value
    :raises: AssertionError if the actual return code is not equal to the expected return code
    """
    if len(result) == 3:
        (_, return_code, msg) = result
    else:
         (return_code, msg) = result

    self.assertEqual(return_code, expected_return_code, msg=msg)
```

So, in the ```test_pol_destroy``` example above, we would do something like:

```
    def test_pool_destroy(self):
        """
        Test destroying a pool.
        """
        pool_name = p_n()
        make_test_pool(pool_name, StratisCertify.DISKS[0:1])

        self.unittest_command(StratisDbus.pool_destroy(pool_name), dbus.UInt16(0))

        self.assertEqual(StratisDbus.fs_list(), {})
```

**Comment by mulkieran** [comment]
@jbaublitz I'ld like this work begun soon, in order to help clear up additional testing errors that we may experience in the blackbox tests. The question is, will this interfere with you work on #510 at this time? If it would, then I had better assign it to you. If not, then I'ld like to assign it to someone else so that you can focus on the D-Bus and encryption specific work in #510 .

**Comment by jbaublitz** [comment]
@mulkieran This doesn't seem invasive enough to cause real problems with #510.

**Comment by bgurney-rh** [comment]
On a test run, I see this now:
```
FAIL: test_pool_add_data (__main__.StratisCertify)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "stratis-cli-77.77.77/tests/blackbox/stratis_cli_cert.py", line 236, in test_pool_add_data
    True,
  File "stratis-cli-77.77.77/tests/blackbox/stratis_cli_cert.py", line 102, in unittest_command
    msg=os.linesep.join(["", "stdout: %s" % stdout, "stderr: %s" % stderr]),
AssertionError: 1 != 0 : 
stdout: 
stderr: Execution failed:
stratisd reported that it did not execute every action that it would have been expected to execute as a result of the command that you requested: Expected to add the specified blockdevs to the data tier in pool STRATI$_DE$TROY_ME!_poolGPOW but stratisd reports that it did not actually add some or all of the blockdevs requested 
```

**Comment by mulkieran** [comment]
Ok!
