### ISSUE TITLE
Error when try to create new pool

### ISSUE THREAD

**Issue by karankevich-aleksey** [stratis-storage/stratis-cli#647]
When i have tried to create new pool i got this error.

Operating System: CentOS Linux 8 (Core)
CPE OS Name: cpe:/o:centos:centos:8
Kernel: Linux 4.18.0-193.19.1.el8_2.x86_64

Python 3.6.8

Stratis-cli version: 2.1.1

Executed command : **stratis pool create new /dev/sdd**

```
stratis encountered an unexpected error during execution. Please report the error and include in your report the stack trace shown below.

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dbus_python_client_gen/_invokers.py", line 68, in dbus_func
    timeout=timeout)
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownInterface: Unknown interface org.storage.stratis2.Manager.r1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/stratis_cli/_main.py", line 43, in the_func
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/stratis_cli/_parser/_parser.py", line 86, in wrapped_func
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/stratis_cli/_actions/_stratisd_version.py", line 38, in check_stratisd_version
  File "/usr/lib/python3.6/site-packages/dbus_python_client_gen/_invokers.py", line 75, in dbus_func
    DPClientGetPropertyContext(name)) from err
dbus_python_client_gen._errors.DPClientInvocationError: Error while getting value for property "Version" belonging to interface "org.storage.stratis2.Manager.r1"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/stratis", line 4, in <module>
    __import__('pkg_resources').run_script('stratis-cli==2.1.1', 'stratis')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/EGG-INFO/scripts/stratis", line 35, in <module>
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/EGG-INFO/scripts/stratis", line 32, in main
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/stratis_cli/_main.py", line 65, in the_func
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/stratis_cli/_error_reporting.py", line 289, in handle_error
  File "/usr/local/lib/python3.6/site-packages/stratis_cli-2.1.1-py3.6.egg/stratis_cli/_main.py", line 60, in the_func
stratis_cli._errors.StratisCliActionError: Action selected by command-line arguments ['pool', 'create', 'new', '/dev/sdd'] which were parsed to Namespace(blockdevs=['/dev/sdd'], func=<function add_subcommand.<locals>.wrap_func.<locals>.wrapped_func at 0x7fe10cf36510>, key_desc=None, pool_name='new', propagate=False, redundancy='none') failed
```

**Comment by jbaublitz** [comment]
Hi @karankevich-aleksey, what version of stratisd are you running?

**Comment by drckeefe** [comment]
To get the version of the Stratis daemon use this command
# /usr/libexec/stratisd --version
stratis 2.1.0

To get the version of Stratis CLI use this command
# stratis --version
2.1.1

**Comment by mulkieran** [comment]
I've confirmed that the stack trace above is that which one would expect to obtain when running stratis 2.1.0 against stratisd 2.0.0. I think that the solution is to raise an exception specifically in stratisd_version.py to warn the user. That's a bit less work than using a minimalist version of the 0th revision of the Manager interface for the version check. I'm going to give that a try.

**Comment by mulkieran** [comment]
@karankevich-aleksey thanks for the report, and helping us improve our code.
