### ISSUE TITLE
don't print traceback on error

### ISSUE THREAD

**Issue by trgill** [stratis-storage/stratis-cli#66]
Currently if a device is suspected of being used by another application, we print: 

Traceback (most recent call last):
  File "/usr/bin/stratis", line 4, in <module>
    __import__('pkg_resources').run_script('stratis-cli==0.0.2', 'stratis')
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1517, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.5/site-packages/stratis_cli-0.0.2-py3.5.egg/EGG-INFO/scripts/stratis", line 32, in <module>
  File "/usr/lib/python3.5/site-packages/stratis_cli-0.0.2-py3.5.egg/EGG-INFO/scripts/stratis", line 29, in main
  File "/usr/lib/python3.5/site-packages/stratis_cli-0.0.2-py3.5.egg/stratis_cli/_main.py", line 36, in the_func
  File "/usr/lib/python3.5/site-packages/stratis_cli-0.0.2-py3.5.egg/stratis_cli/_actions/_top.py", line 60, in create_pool
stratis_cli._errors.StratisCliRuntimeError: 1: Device /dev/sdg appears to belong to another application

**Comment by stardude900** [comment]
I know some Python, is stratis-cli open to PRs from anyone?  This looks kinda like low hanging fruit that I could probably do

**Comment by agrover** [comment]
Heck yeah!

**Comment by mulkieran** [comment]
We need to make the ```propagate``` default False.
